word_count.out: word_count.c
	gcc `pkg-config --cflags --libs glib-2.0` -g -o word_count.out word_count.c

ex_compile.o: ex_compile.c
	gcc `pkg-config --cflags --libs glib-2.0` -o ex_compile.o ex_compile.c
